"""Backward-compatible configuration facade.

Canonical configuration code lives in :mod:`coal_kb.infra.config`.
"""

from coal_kb.infra.config import (
    PathsConfig,
    LocalEmbeddingConfig,
    ChunkingProfile,
    ChunkingConfig,
    ChromaConfig,
    TwoStageRetrievalConfig,
    PDFMarkdownConfig,
    RetrievalConfig,
    RerankConfig,
    LoggingConfig,
    RegistryConfig,
    ElasticConfig,
    IngestionConfig,
    TenancyConfig,
    ModelVersionsConfig,
    QueryRewriteConfig,
    LLMConfig,
    RemoteEmbeddingsConfig,
    AppConfig,
    EnvSettings,
    _ensure_dirs,
    _load_yaml_unique_keys,
    load_config,
)

__all__ = [
    "PathsConfig",
    "LocalEmbeddingConfig",
    "ChunkingProfile",
    "ChunkingConfig",
    "ChromaConfig",
    "TwoStageRetrievalConfig",
    "PDFMarkdownConfig",
    "RetrievalConfig",
    "RerankConfig",
    "LoggingConfig",
    "RegistryConfig",
    "ElasticConfig",
    "IngestionConfig",
    "TenancyConfig",
    "ModelVersionsConfig",
    "QueryRewriteConfig",
    "LLMConfig",
    "RemoteEmbeddingsConfig",
    "AppConfig",
    "EnvSettings",
    "load_config",
    "_ensure_dirs",
    "_load_yaml_unique_keys",
]
