"""维护复杂科学问答实际使用的确定性参数。"""

# 路由与分解
MAX_SUBQUERIES = 4
MAX_MULTI_HOP_STEPS = 3

# 检索预算
COMPARISON_K_PER_SIDE = 4
CROSS_DOCUMENT_MIN_SOURCES = 2
CROSS_DOCUMENT_MAX_PER_SOURCE = 2
TABLE_TOP_K = 5
AGGREGATION_RECORD_LIMIT = 500
AGGREGATION_EVIDENCE_LIMIT = 12

# 数据路径
TABLE_RECORDS_PATH = "data/interim/table_records.jsonl"

# 可复现性
SAMPLE_SEED = 20260715
